#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := main

EXTRA_COMPONENT_DIRS := $(abspath ssd1306_spi)  $(abspath disp_spi)  $(abspath tcp_app)

include $(IDF_PATH)/make/project.mk

